### ISSUE TITLE
Server Response?

### ISSUE THREAD

**Issue by piboistudios** [andyli/hxudp#7]
I was able to set up a client and server, and I was able to send data to the server and have a sprite on the server track a sprite on the client, however I could not send data from the server back to the client (which was the natural next step, as I wanted to make the client's sprite only move when movement was successfully tracked and reported by the server)

I also couldn't get multicasting to work (it just crashed whenever attempting to receive from multicast, however I could connect two instances to a multicast group and send data to the group, just not receive it)

I know that this is an unstable API, but I was just wondering, is responding to communication from another socket possible? Or sending data directly to a connected socket?

**Comment by andyli** [comment]
This lib is quite old and I haven't really used it production, despite there seems to be many people used (or wanted to use) it.
Have you tried [`sys.net.UdpSocket`](https://api.haxe.org/sys/net/UdpSocket.html) in the standard library? Hopefully it will just work for you and you may simply use that instead of hxudp. If not, I will see if there is anything I can do (UdpSocket or hxudp).

**Comment by piboistudios** [comment]
I have not. I assumed because the source code was functionally blank on the website it was an unfinished API. Am I mistaken?

EDIT: Yeah, it just seems all the `sys.net` files are basically just header files right now. 

EDIT EDIT: Upon further inspection (which wasn't really much at all, I guess I just wasn't really looking) there is a section on Remoting in the [Haxe Manual](https://haxe.org/manual/std-remoting-connection.html) which expounds upon the remoting package. And apparently the implementation of the Socket is actually here (and is an alias for `sys.net.Socket`)

Sorry for the silly inquiry haha.

EDIT: Also read up on externs. As `sys.net.Socket` is an external class, which I completely missed.
